name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      # Add your build steps here if needed (npm install, build commands, etc.)
      # Example:
      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Build project
      #   run: npm run build

      - name: Upload website to artifact
        uses: actions/upload-pages-artifact@v3  # Updated to v3
        with:
          path: ./  # or your build directory like 'dist/', 'public/', etc.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3  # Updated to v3