name: test ci/cd

on:
  schedule:
    - cron: '0 0 * * *'  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sast-codeql:
    name: Static Analysis (SAST) with CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

 