name: Deploy Website to GitHub Pages

on:
  push:
    branches: [ master ]  # or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Add your build commands here if needed
      # - run: npm install && npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: website-artifact
          path: ./  # or your build directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3